_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.4
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
ignore_chirality:
    value: true
threshold:
    value: 0.5
